CREATE DATABASE guaradb;
CREATE USER guarauser WITH PASSWORD 'YOUR_PASSWORD_HERE';

GRANT ALL PRIVILEGES ON DATABASE guaradb TO guarauser;
ALTER SCHEMA public OWNER TO guarauser;
GRANT USAGE ON SCHEMA public TO guarauser; 
GRANT CREATE ON SCHEMA public TO guarauser;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO guarauser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO guarauser; 
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO guarauser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO guarauser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO guarauser;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO guarauser;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

ALTER DATABASE guaradb OWNER TO guarauser;

CREATE EXTENSION IF NOT EXISTS pg_trgm;
